CREATE TABLE `fdd_log` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `function_name` varchar(64) DEFAULT NULL COMMENT '方法名',
  `response` text COMMENT '返回值',
  `request_time` datetime DEFAULT NULL COMMENT '请求时间',
  `responese_time` datetime DEFAULT NULL COMMENT '响应时间',
  `ip` varchar(32) DEFAULT NULL COMMENT '请求ip',
  `customer_name` varchar(32) DEFAULT NULL COMMENT '客户姓名',
  `mobile` varchar(11) DEFAULT NULL COMMENT '客户手机号',
  `id_card` varchar(20) DEFAULT NULL COMMENT '证件号码',
  `ident_type` varchar(1) DEFAULT NULL COMMENT '证件类型',
  `contract_id` varchar(32) DEFAULT NULL COMMENT '合同编号',
  `template_id` varchar(32) DEFAULT NULL COMMENT '模板编号',
  `doc_title` varchar(64) DEFAULT NULL COMMENT '文档标题',
  `font_size` varchar(2) DEFAULT NULL COMMENT '字体大小',
  `font_type` varchar(1) DEFAULT NULL COMMENT '字体类型',
  `parameter_map` text COMMENT '填充内容',
  `dynamic_tables` text COMMENT '动态表格',
  `coustomer_sign_keyword` varchar(32) DEFAULT NULL COMMENT '客户签定位关键字',
  `company_sign_keyword` varchar(32) DEFAULT NULL COMMENT '公司签定位关键字',
  `email` varchar(64) DEFAULT NULL,
  `source` varchar(2) DEFAULT NULL COMMENT '来源',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=46 DEFAULT CHARSET=utf8;